name: Auto Commit from Folder

on:
  schedule:
    - cron: '0 18 * * *'  # Runs daily at 6 PM UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps: #This clones GitHub repository into the GitHub runner so it can access files.
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git #Sets up Git with a bot identity to commit changes.
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Detect changes in folder
        id: changes
        run: |
          git add leetcode/
          if git diff --cached --quiet; then
            echo "No changes"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push if changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git commit -m "Automated commit from 'leetcode' at 6 PM"
          git push
